FROM golang:1.20 as build
ADD hackathon /
CMD [ "/hackathon" ]

#FROM golang:1.20 as build
#WORKDIR /hackathon
#COPY ./ .
#RUN go mod init hackathon && go mod tidy
#RUN go build -o . hackathon/
#CMD ["./hackathon"]