CREATE TABLE channel (
  id CHAR(36) PRIMARY KEY,
  workspaceId CHAR(36) NOT NULL,
  name VARCHAR(255) NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  bio CHAR(255),
  publicPw CHAR(255),
  privatePw CHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workspace (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  bio CHAR(255),
  img CHAR(255),
  publicPw CHAR(255),
  privatePw CHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user (
  id CHAR(36) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  deleted BOOLEAN NOT NULL DEFAULT FALSE,
  bio CHAR(255),
  img CHAR(255),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE userChannel (
  userId CHAR(36) NOT NULL,
  channelId CHAR(36) NOT NULL,
  owner BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (userId, channelId)
);

CREATE TABLE userWorkspace (
  userId CHAR(36) NOT NULL,
  workspaceId CHAR(36) NOT NULL,
  owner BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (userId, workspaceId)
);

CREATE TABLE message (
  id CHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  postedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  postedBy CHAR(36) NOT NULL,
  channelId CHAR(36) NOT NULL,
  edited BOOLEAN NOT NULL DEFAULT FALSE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE reply (
  id CHAR(36) PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  body TEXT NOT NULL,
  postedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  postedBy CHAR(36) NOT NULL,
  replyTo CHAR(36) NOT NULL,
  edited BOOLEAN NOT NULL DEFAULT FALSE,
  deleted BOOLEAN NOT NULL DEFAULT FALSE
);
