version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql
    platform: linux/x86_64
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hackathon
      MYSQL_USER: uttc
      MYSQL_PASSWORD: password
      LC_ALL: C.UTF-8
